### ISSUE TITLE
Port to the Meson build system

### ISSUE THREAD

**Issue by t-chaik** [hughsie/colord-gtk#10]
Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible. Porting modules to Meson is a [GNOME Goal](https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting).

**Comment by mcatanzaro** [comment]
This broke gnome-build-meta. I'll fix it for you, but I need you to please promise a new tarball by Monday, June 25 (next GNOME tarball deadline) to avoid causing problems for the release manager. Thanks!

P.S. This should probably be closed.

**Comment by mcatanzaro** [comment]
> This broke gnome-build-meta. I'll fix it for you

Javier beat me to it. Still need that release. Thanks!

**Comment by alatiera** [comment]
> Monday, June 25

It was actually June 17 :P

Also, please try to not drop autotools at the same commit that introduces the new build system, it makes it harder to switch if there's a regression or bug in meson.

**Comment by hughsie** [comment]
> Also, please try to not drop autotools at the same commit that introduces the new build system

I tried supporting two build systems in one project and it was a disaster. I'll roll a new tarball today with the meson-ified build.

**Comment by hughsie** [comment]
There is a gtk regression that's preventing me run the tests on F30: https://gitlab.gnome.org/GNOME/gtk/issues/1961 -- I'll wait until that's fixed before doing the tarball as we might have to use a different API rather than `get_plug_name`.
