### ISSUE TITLE
0.2.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [hughsie/colord-gtk#13]
<pre>+ /usr/bin/ninja test -v -j 48 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu&apos;
[0/1] /usr/bin/meson test --no-rebuild --print-errorlogs
<font color="#CC0000"><b>1/1 colord-test-private                     FAIL     0.52 s (killed by signal 11 SIGSEGV)</b></font>

Ok:                    0
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0

The output from the failed tests:

1/1 colord-test-private                     FAIL     0.52 s (killed by signal 11 SIGSEGV)

--- command ---
/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.2.0/x86_64-redhat-linux-gnu/libcolord-gtk/colord-gtk-test
--- stdout ---
# random seed: R02Sf5fe65c86d92186627b82e166b4ff32b
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
1..2
# Start of colord tests
-------

Full log written to /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.2.0/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
</pre>

**Comment by hughsie** [comment]
Got a backtrace?

**Comment by kloczek** [comment]
Will take later when will back home :)
