### ISSUE TITLE
Question: New release expected soon?

### ISSUE THREAD

**Issue by pabloyoyoista** [hughsie/colord-gtk#17]
Dear maintainers,

With recent changes, specifically the gtk4 support and considering that there hasn't been a release for 2 years, are there any plans to tag a new release? I understand that there might be a lot of reasons for not doing a release and distros can in principle just package latest master. In my case packaging master needs some justification, but I could not find any statement or release schedule. Would it be possible to know if there are any plans to prepare a release in the following weeks/months?

Thank you very much for your time.

**Comment by hughsie** [comment]
We probably need to discuss https://github.com/hughsie/colord-gtk/pull/18 before tagging a release.

**Comment by pabloyoyoista** [comment]
Thanks a lot for the reply. Will monitor it.

**Comment by pabloyoyoista** [comment]
New release is out, thank you!
