### ISSUE TITLE
Migrate from Intltool to Gettext

### ISSUE THREAD

**Issue by t-chaik** [hughsie/colord-gtk#5]
Recent gettext versions can extract and merge back strings from and to various file formats, not need for deprecated intltool any more. Migrating modules to gettext is a [GNOME Goal](https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration).

**Comment by hughsie** [comment]
I'd much rather migrate to meson, then we get the gettext conversion for free.

**Comment by t-chaik** [comment]
Agreed, a Meson port would be nice. I've opened https://github.com/hughsie/colord-gtk/issues/10 for that. Some adjustments probably still are necessary for full gettext though. I'll write a first patch for gettext and then give the Meson port a try.

**Comment by t-chaik** [comment]
Patch is here https://github.com/hughsie/colord-gtk/pull/11.
