### ISSUE TITLE
0.1.26: automake warnings

### ISSUE THREAD

**Issue by kloczek** [hughsie/colord-gtk#8]
<pre>configure.ac:115: warning: The &apos;AM_PROG_MKDIR_P&apos; macro is deprecated, and its use is discouraged.
configure.ac:115: You should use the Autoconf-provided &apos;AC_PROG_MKDIR_P&apos; macro instead,
configure.ac:115: and use &apos;$(MKDIR_P)&apos; instead of &apos;$(mkdir_p)&apos;in your Makefile.am files.
</pre>

**Comment by hughsie** [comment]
This is a really dumb warning from automake that I don't think it's possible to remove. When we switch to meson this will go away.
