### ISSUE TITLE
0.1.26: color-gtk uses deprecated glib and gtk API

### ISSUE THREAD

**Issue by kloczek** [hughsie/colord-gtk#9]
```
$ rpm -q glib2 gtk3
glib2-2.61.0-3.fc31.x86_64
gtk3-3.24.8-3.fc31.x86_64

```
All build warnings extracted from build log:
<pre>cd-sample-window.c: In function &apos;cd_sample_window_class_init&apos;:
cd-sample-window.c:124:2: warning: &apos;g_type_class_add_private&apos; is deprecated [-Wdeprecated-declarations]
  124 |  g_type_class_add_private (klass, sizeof (CdSampleWindowPrivate));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from cd-sample-window.c:24:
/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 1303 | void     g_type_class_add_private       (gpointer                    g_class,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile_finish&apos;:
cd-window.c:142:2: warning: &apos;g_simple_async_result_propagate_error&apos; is deprecated [-Wdeprecated-declarations]
  142 |  if (g_simple_async_result_propagate_error (simple, error))
      |  ^~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:119:21: note: declared here
  119 | gboolean            g_simple_async_result_propagate_error  (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:145:2: warning: &apos;g_simple_async_result_get_op_res_gpointer&apos; is deprecated [-Wdeprecated-declarations]
  145 |  return g_object_ref (g_simple_async_result_get_op_res_gpointer (simple));
      |  ^~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:79:21: note: declared here
   79 | gpointer            g_simple_async_result_get_op_res_gpointer (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:145:2: warning: &apos;g_simple_async_result_get_op_res_gpointer&apos; is deprecated [-Wdeprecated-declarations]
  145 |  return g_object_ref (g_simple_async_result_get_op_res_gpointer (simple));
      |  ^~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:79:21: note: declared here
   79 | gpointer            g_simple_async_result_get_op_res_gpointer (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile_client_connect_cb&apos;:
cd-window.c:172:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  172 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:177:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  177 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile_device_connect_cb&apos;:
cd-window.c:198:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  198 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:203:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  203 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:212:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  212 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:217:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  217 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile_profile_connect_cb&apos;:
cd-window.c:239:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  239 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:244:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  244 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:253:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  253 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:257:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  257 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:263:2: warning: &apos;g_simple_async_result_set_op_res_gpointer&apos; is deprecated [-Wdeprecated-declarations]
  263 |  g_simple_async_result_set_op_res_gpointer (helper-&gt;res,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:75:21: note: declared here
   75 | void                g_simple_async_result_set_op_res_gpointer (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:266:2: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  266 |  g_simple_async_result_complete_in_idle (helper-&gt;res);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile_device_find_cb&apos;:
cd-window.c:284:3: warning: &apos;g_simple_async_result_set_error&apos; is deprecated [-Wdeprecated-declarations]
  284 |   g_simple_async_result_set_error (helper-&gt;res,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:122:21: note: declared here
  122 | void                g_simple_async_result_set_error        (GSimpleAsyncResult      *simple,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:289:3: warning: &apos;g_simple_async_result_complete_in_idle&apos; is deprecated [-Wdeprecated-declarations]
  289 |   g_simple_async_result_complete_in_idle (helper-&gt;res);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:106:21: note: declared here
  106 | void                g_simple_async_result_complete_in_idle (GSimpleAsyncResult      *simple);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_update_widget_plug_name&apos;:
cd-window.c:388:2: warning: &apos;gdk_screen_get_monitor_at_window&apos; is deprecated: Use &apos;gdk_display_get_monitor_at_window&apos; instead [-Wdeprecated-declarations]
  388 |  monitor_num = gdk_screen_get_monitor_at_window (screen,
      |  ^~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from cd-window.c:36:
/usr/include/gtk-3.0/gdk/gdkscreen.h:91:15: note: declared here
   91 | gint          gdk_screen_get_monitor_at_window (GdkScreen *screen,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:390:2: warning: &apos;gdk_screen_get_monitor_plug_name&apos; is deprecated: Use &apos;gdk_monitor_get_model&apos; instead [-Wdeprecated-declarations]
  390 |  plug_name = gdk_screen_get_monitor_plug_name (screen, monitor_num);
      |  ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from cd-window.c:36:
/usr/include/gtk-3.0/gdk/gdkscreen.h:100:15: note: declared here
  100 | gchar *       gdk_screen_get_monitor_plug_name (GdkScreen *screen,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_get_profile&apos;:
cd-window.c:443:2: warning: &apos;g_simple_async_result_new&apos; is deprecated: Use &apos;g_task_new&apos; instead [-Wdeprecated-declarations]
  443 |  helper-&gt;res = g_simple_async_result_new (G_OBJECT (window),
      |  ^~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:117,
                 from cd-window.c:34:
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:51:21: note: declared here
   51 | GSimpleAsyncResult *g_simple_async_result_new              (GObject                 *source_object,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c: In function &apos;cd_window_class_init&apos;:
cd-window.c:523:2: warning: &apos;g_type_class_add_private&apos; is deprecated [-Wdeprecated-declarations]
  523 |  g_type_class_add_private (klass, sizeof (CdWindowPrivate));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from cd-window.c:34:
/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 1303 | void     g_type_class_add_private       (gpointer                    g_class,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
cd-sample-widget.c: In function &apos;cd_sample_window_enter_notify_event_cb&apos;:
cd-sample-widget.c:152:2: warning: &apos;gdk_cursor_new&apos; is deprecated: Use &apos;gdk_cursor_new_for_display&apos; instead [-Wdeprecated-declarations]
  152 |  cursor = gdk_cursor_new (GDK_BLANK_CURSOR);
      |  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdk.h:34,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from cd-sample-widget.c:24:
/usr/include/gtk-3.0/gdk/gdkcursor.h:228:12: note: declared here
  228 | GdkCursor* gdk_cursor_new   (GdkCursorType    cursor_type);
      |            ^~~~~~~~~~~~~~
cd-sample-widget.c: In function &apos;cd_sample_window_leave_notify_event_cb&apos;:
cd-sample-widget.c:170:2: warning: &apos;gdk_cursor_new&apos; is deprecated: Use &apos;gdk_cursor_new_for_display&apos; instead [-Wdeprecated-declarations]
  170 |  cursor = gdk_cursor_new (GDK_ARROW);
      |  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdk.h:34,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from cd-sample-widget.c:24:
/usr/include/gtk-3.0/gdk/gdkcursor.h:228:12: note: declared here
  228 | GdkCursor* gdk_cursor_new   (GdkCursorType    cursor_type);
      |            ^~~~~~~~~~~~~~
cd-sample-widget.c: In function &apos;cd_sample_widget_class_init&apos;:
cd-sample-widget.c:190:2: warning: &apos;g_type_class_add_private&apos; is deprecated [-Wdeprecated-declarations]
  190 |  g_type_class_add_private (class, sizeof (CdSampleWidgetPrivate));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from cd-sample-widget.c:24:
/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 1303 | void     g_type_class_add_private       (gpointer                    g_class,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
cd-window.c:505: Warning: ColordGtk: incorrect number of parameters in comment block, parameter annotations will be ignored.
</pre>

**Comment by hughsie** [comment]
If you want to port this away from the deprecated API then please open a pull request -- it's not on my TODO, sorry.
